#!/usr/bin/env node
'use strict';

const program = require('commander');
const call = require('./src/gll/operations');

program.version('0.1.0');

program
    .command("create <repo-name>")
    .option('-r, --region [region]', 'AWS region to use', 'us-west-2')
    .description("Create and deploy a new repo endpoint")
    .action(call.generate);

program
    .command('delete <repo-name>')
    .option('-r, --region [region]', 'AWS region to use', 'us-west-2')
    .description("Delete an existing repo endpoint")
    .action(call.delete);

program
    .command('*')
    .action(() => {
        console.log("No valid command found.")
        program.outputHelp();
    });

program.parse(process.argv);

