AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless AWS implementation of the GIT-LFS server spec.

Globals:
  Function:
    Runtime: nodejs6.10

Parameters:
  deploymentBucketName:
    Type: String

Resources:
  batch:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: '${repoName}-batch'
      Handler: batch.handler
      CodeUri:
        Bucket: !Ref deploymentBucketName
        Key: batch
      Events:
        Api:
          Type: Api
          Properties:
            Path: /${repoName}.git/info/lfs/objects/batch
            Method: POST
  verifyLocks:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: '${repoName}-verifyLocks'
      Handler: verifyLocks.handler
      CodeUri:
        Bucket: !Ref deploymentBucketName
        Key: verifyLocks
      Events:
        Api:
          Type: Api
          Properties:
            Path: ${repoName}.git/info/lfs/locks/verify
            Method: POST
  listLocks:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: '${repoName}-listLocks'
      Handler: listLocks.handler
      CodeUri:
        Bucket: !Ref deploymentBucketName
        Key: listLocks
      Events:
        Api:
          Type: Api
          Properties:
            Path: /${repoName}.git/info/lfs/locks
            Method: GET
  createLock:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: '${repoName}-createLock'
      Handler: createLock.handler
      CodeUri:
        Bucket: !Ref deploymentBucketName
        Key: createLock
      Events:
        Api:
          Type: Api
          Properties:
            Path: /${repoName}.git/info/lfs/locks
            Method: POST
  deleteLock:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: '${repoName}-deleteLock'
      Handler: deleteLock.handler
      CodeUri:
        Bucket: !Ref deploymentBucketName
        Key: deleteLock
      Events:
        Api:
          Type: Api
          Properties:
            Path: /${repoName}.git/info/lfs/locks/{id}/unlock
            Method: POST

