AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless AWS implementation of the GIT-LFS server spec.

Parameters:
  bucketName:
    Type: String

Resources:
  artifactsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: Private
      BucketName: !Ref bucketName
  batch:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: '${repoName}-batch'
      Runtime: nodejs6.10
      Timeout: 60
      Handler: batch.handler
      CodeUri: ${batchUri}
      Policies:
        - S3CrudPolicy:
          BucketName: !Ref artifactsBucket
      Events:
        Api:
          Type: Api
          Properties:
            Path: /${repoName}.git/info/lfs/objects/batch
            Method: POST
  verifyLocks:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: '${repoName}-verifyLocks'
      Runtime: nodejs6.10
      Timeout: 60
      Handler: verifyLocks.handler
      CodeUri: ${verifyLocksUri}
      Events:
        Api:
          Type: Api
          Properties:
            Path: /${repoName}.git/info/lfs/locks/verify
            Method: POST
  listLocks:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: '${repoName}-listLocks'
      Runtime: nodejs6.10
      Timeout: 60
      Handler: listLocks.handler
      CodeUri: ${listLocksUri}
      Events:
        Api:
          Type: Api
          Properties:
            Path: /${repoName}.git/info/lfs/locks
            Method: GET
  createLock:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: '${repoName}-createLock'
      Runtime: nodejs6.10
      Timeout: 60
      Handler: createLock.handler
      CodeUri: ${createLockUri}
      Events:
        Api:
          Type: Api
          Properties:
            Path: /${repoName}.git/info/lfs/locks
            Method: POST
  deleteLock:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: '${repoName}-deleteLock'
      Runtime: nodejs6.10
      Timeout: 60
      Handler: deleteLock.handler
      CodeUri: ${deleteLockUri}
      Events:
        Api:
          Type: Api
          Properties:
            Path: /${repoName}.git/info/lfs/locks/{id}/unlock
            Method: POST

